from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

with webdriver.Chrome(executable_path="C:/WebDriver/bin/chromedriver_v97_win32/chromedriver.exe") as driver:
    driver.get("https://une.adminfo.net/vsmart/")
    elemento = driver.find_element(by=By.NAME, value="usuario")
    elemento.send_keys("aarevalo")
    elemento = driver.find_element(by=By.NAME, value="clave")
    elemento.send_keys("Tony2021/*-+02")
    elemento.submit()
    elemento = driver.find_element(by=By.LINK_TEXT, value="Gestión")
    elemento.click()
    elemento = driver.find_element(by=By.LINK_TEXT, value="Coordinador Andes Bpo")
    elemento.click()
    elemento = driver.find_element(by=By.LINK_TEXT, value="Informes Principales")
    elemento.click()
    elemento = driver.find_element(by=By.LINK_TEXT, value="Informe General De Cartera")
    elemento.click()
    elemento = driver.find_element(by=By.ID, value="s2id_col")
    elemento.click()
    elemento = driver.find_element(by=By.PARTIAL_LINK_TEXT, value="Consecutivo Traslado")
    elemento.click()
    elemento = driver.find_element(by=By.ID, value="s2id_ope")
    elemento.click()
    elemento.send_keys("Incluya")
    elemento.submit()
    elemento = driver.find_element(by=By.ID, value="valor")
    elemento.send_keys("495::496::497::523")
    elemento = driver.find_element(by=By.ID, value="btnAgregarCriterio")
    elemento.click()
    elemento = driver.find_element(by=By.ID, value="s2id_agrupador")
    elemento.click()
    elemento.send_keys("Detalle en Pantalla")
    elemento.submit()
    elemento = driver.find_element(by=By.ID, value="add_tab")
    elemento.click()
    elemento = driver.find_element(by=By.CLASS_NAME, value="fa fa-list-alt fa-4x colorAzulOscuro")
    elemento.click()
    elemento = driver.find_element(by=By.CLASS_NAME, value="ui-pg-selbox")
    elemento.click()
    elemento = driver.find_element(by=By.LINK_TEXT, value=400000)
    print(driver.current_url)
